# coding = utf-8
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
HACHAT_VERSION = 0.1
HACHAT_HEADER = "HACHAT VER" + str(HACHAT_VERSION)
HACHAT_BUFSIZE = 1024
MAINTENANCE_SLEEP = 20 # sleep x seconds between maintenance periods
MIN_PEERLIMIT = 15
INI_PEERLIMIT = 3
HISTORY_SAVEDMSGSLIMIT = 30
HISTORY_SAVEDHASHESLIMIT = 100
HISTORY_GETLIMIT = 30
HISTORY_INIGETLIMIT = 20
